# Generated by Django 4.1 on 2025-05-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type_user',
            field=models.CharField(default='PC', max_length=60),
            preserve_default=False,
        ),
    ]
