# Generated by Django 4.1 on 2025-12-02 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacanceHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_start', models.DateField()),
                ('date_ends', models.DateField()),
                ('days_taken', models.IntegerField()),
                ('days_remains', models.IntegerField()),
                ('date_restart', models.DateField()),
                ('date_restart_real', models.DateField()),
                ('vacance_type', models.CharField(max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharm.personnel')),
            ],
        ),
    ]
