# Generated by Django 4.1 on 2025-03-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0002_medicament_medic_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='lot_number',
            field=models.CharField(default='lot', max_length=150),
            preserve_default=False,
        ),
    ]
