# Generated by Django 4.1 on 2025-03-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0003_stock_lot_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='medic_price',
        ),
        migrations.AddField(
            model_name='stock',
            name='medic_lot_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
