# Generated by Django 4.1 on 2025-04-30 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0004_remove_medicament_medic_price_stock_medic_lot_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arivage_items',
            name='date_expired',
        ),
        migrations.AddField(
            model_name='arivage',
            name='bon_arrivage_nbr',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arivage',
            name='fourn',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pharm.fournisseur'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arivage_items',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharm.stock'),
        ),
    ]
