# Generated by Django 4.1 on 2025-04-30 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0005_remove_arivage_items_date_expired_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arivage',
            name='source_detail',
        ),
    ]
