# Generated by Django 4.1 on 2025-06-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0006_remove_arivage_source_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article_code', models.CharField(max_length=100)),
                ('article_name', models.CharField(max_length=100)),
                ('article_type', models.CharField(max_length=100)),
            ],
        ),
    ]
