# Generated by Django 4.1 on 2025-06-26 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0007_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='QntConv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('qntMax', models.DecimalField(decimal_places=2, max_digits=20)),
                ('qntMin', models.DecimalField(decimal_places=2, max_digits=20)),
                ('prixUnit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tva', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharm.article')),
            ],
        ),
    ]
