# Generated by Django 4.1 on 2025-06-30 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0008_qntconv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consomation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('cons', models.DecimalField(decimal_places=2, max_digits=20)),
                ('qnt_conv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharm.qntconv')),
            ],
        ),
    ]
