# Generated by Django 4.1 on 2025-07-09 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0011_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharm.grade')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharm.service')),
            ],
        ),
    ]
