# Generated by Django 4.1 on 2025-11-28 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharm', '0012_personnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='vacance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_start', models.DateField()),
                ('date_ends', models.DateField()),
                ('days_taken', models.IntegerField()),
                ('days_remains', models.IntegerField()),
                ('date_restart', models.DateField()),
                ('vacance_type', models.CharField(max_length=100)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharm.personnel')),
            ],
        ),
        migrations.RemoveField(
            model_name='arivage_items',
            name='arivage',
        ),
        migrations.RemoveField(
            model_name='arivage_items',
            name='medicament',
        ),
        migrations.RemoveField(
            model_name='bon_commande',
            name='fournisseur',
        ),
        migrations.RemoveField(
            model_name='bon_sortie',
            name='source',
        ),
        migrations.RemoveField(
            model_name='commande_items',
            name='bon_commande',
        ),
        migrations.RemoveField(
            model_name='commande_items',
            name='medicament',
        ),
        migrations.RemoveField(
            model_name='consomation',
            name='qnt_conv',
        ),
        migrations.RemoveField(
            model_name='qntconv',
            name='article',
        ),
        migrations.RemoveField(
            model_name='repas',
            name='service',
        ),
        migrations.RemoveField(
            model_name='sortie_items',
            name='bon_sortie',
        ),
        migrations.RemoveField(
            model_name='sortie_items',
            name='med_sortie',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='medicament',
        ),
        migrations.DeleteModel(
            name='Arivage',
        ),
        migrations.DeleteModel(
            name='Arivage_items',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Bon_commande',
        ),
        migrations.DeleteModel(
            name='Bon_sortie',
        ),
        migrations.DeleteModel(
            name='Commande_items',
        ),
        migrations.DeleteModel(
            name='Consomation',
        ),
        migrations.DeleteModel(
            name='Fournisseur',
        ),
        migrations.DeleteModel(
            name='Medicament',
        ),
        migrations.DeleteModel(
            name='QntConv',
        ),
        migrations.DeleteModel(
            name='Repas',
        ),
        migrations.DeleteModel(
            name='Sortie_items',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
